{
 "title": "s3bucket",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "s3name", "query": "label_values(s3name)" }
  ]
 },
 "panels": [
  {
   "title": "s3 status",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "s3_endpoint_up{s3name=\"$s3name\"}"
    }
   ]
  },
  {
   "title": "s3 total object number",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "s3_total_object_number{s3name=\"$s3name\"}"
    }
   ]
  },
  {
   "title": "s3 usage",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "s3_total_size{s3name=\"$s3name\"}"
    }
   ]
  },
  {
   "title": "s3 usage per bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "s3_bucket_size{s3name=\"$s3name\"}",
     "legendFormat": "{{ bucketname }}"
    }
   ]
  },
  {
   "title": "s3 total object number",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "s3_bucket_object_number{s3name=\"$s3name\"}",
     "legendFormat": "{{ bucketname }}"
    }
   ]
  }
 ]
}